name: advent_of_code
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/ObNitram/advent_of_code.git
publish_to: none

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  log_tanker: ^0.0.2
  path: ^1.8.0

  obni_utils:
    path: packages/obni_utils



dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
